version: '3'

services:
  postgres:
    container_name: db
    image: postgres:14.5
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/.data/postgres:/var/lib/postgresql/data
      - ./script/load-extensions.sh:/docker-entrypoint-initdb.d/load-extensions.sh
    restart: unless-stopped
    environment:
      POSTGRES_USER: "nestjs"
      POSTGRES_PASSWORD: "nestjs"
      POSTGRES_DB: "boilerplate-db"
    networks:
      - boilerplate_net
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: nestjs@boilerplate.com
      PGADMIN_DEFAULT_PASSWORD: nestjs
    volumes:
      - ${HOME}/.data/pgadmin:/root/.pgadmin
    networks:
      - boilerplate_net
    links:
      - postgres
networks:
  boilerplate_net:
    driver: bridge
volumes:
  postgres:
    driver: local