
##config
---
context: "/"
group: nestjs
project: nestjs-boilerplate-project
description: nestjs-boilerplate-project
local:
  common:
    http-port: 3000
    log-level: info
development:
  common:
    http-port: 3000
    log-level: info
production:
  common:
    http-port: 3000
    log-level: info